// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQpWPeBxxNYzarrsUwYy91C6Ha4iFZtJo',
    appId: '1:1036946500500:web:60bcf2414e01e86f5abd81',
    messagingSenderId: '1036946500500',
    projectId: 'rental-ledger-app',
    // The hosting domain, not firebaseapp.com: Google redirect sign-in (used
    // by the iPhone Home Screen app) must return to the app's own site, or
    // Safari's storage blocking loses the result. Keep this if FlutterFire
    // regenerates the file.
    authDomain: 'rental-ledger-app.web.app',
    storageBucket: 'rental-ledger-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsvitE78bCdlMmay1-3gREkerNS0ajnlE',
    appId: '1:1036946500500:android:6642e2ac29b274095abd81',
    messagingSenderId: '1036946500500',
    projectId: 'rental-ledger-app',
    storageBucket: 'rental-ledger-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHbHO6OMC2xHVivUIXacEqxqMfo-a58nc',
    appId: '1:1036946500500:ios:23b805c2a9e539335abd81',
    messagingSenderId: '1036946500500',
    projectId: 'rental-ledger-app',
    storageBucket: 'rental-ledger-app.firebasestorage.app',
    iosClientId: '1036946500500-nl62jc1shrhd9c4mjk0uur45tetc3svd.apps.googleusercontent.com',
    iosBundleId: 'com.rentalledger.rentalLedger',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHbHO6OMC2xHVivUIXacEqxqMfo-a58nc',
    appId: '1:1036946500500:ios:23b805c2a9e539335abd81',
    messagingSenderId: '1036946500500',
    projectId: 'rental-ledger-app',
    storageBucket: 'rental-ledger-app.firebasestorage.app',
    iosClientId: '1036946500500-nl62jc1shrhd9c4mjk0uur45tetc3svd.apps.googleusercontent.com',
    iosBundleId: 'com.rentalledger.rentalLedger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQpWPeBxxNYzarrsUwYy91C6Ha4iFZtJo',
    appId: '1:1036946500500:web:ba0e43410eef4e355abd81',
    messagingSenderId: '1036946500500',
    projectId: 'rental-ledger-app',
    authDomain: 'rental-ledger-app.firebaseapp.com',
    storageBucket: 'rental-ledger-app.firebasestorage.app',
  );
}
